# Generated by Django 5.2.12 on 2026-03-18 23:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulacaoTPV",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nome_contribuinte", models.CharField(blank=True, default="", max_length=300)),
                ("cpf_cnpj", models.CharField(blank=True, default="", max_length=18)),
                (
                    "tipo_porte",
                    models.CharField(
                        choices=[("PF", "Pessoa Física"), ("ME", "Microempresa"), ("EPP", "Empresa de Pequeno Porte")],
                        max_length=5,
                    ),
                ),
                ("salario_minimo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("parcelas_entrada", models.PositiveSmallIntegerField()),
                ("parcelas_saldo", models.PositiveSmallIntegerField()),
                ("resultado", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulacoes_tpv",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulação TPV",
                "verbose_name_plural": "Simulações TPV",
                "ordering": ["-created_at"],
            },
        ),
    ]
