# Generated by Django 5.2.12 on 2026-03-19 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_alter_empresa_unique_together"),
        ("tpv", "0002_simulacaotpv_created_by_simulacaotpv_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulacaotpv",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa vinculada (opcional). Se preenchida, nome/cnpj vem da empresa.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="simulacoes_tpv",
                to="empresas.empresa",
            ),
        ),
    ]
