# Generated by Django 5.2.12 on 2026-03-18 23:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=300)),
                ("cnpj", models.CharField(max_length=18, verbose_name="CNPJ")),
                ("porte", models.CharField(choices=[("ME/EPP", "ME/EPP"), ("DEMAIS", "DEMAIS")], max_length=20)),
                (
                    "honorarios_percentual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Honorários (%)"),
                ),
                ("observacoes", models.TextField(blank=True, null=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="empresas", to="core.organization"
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["nome"],
            },
        ),
    ]
