# Generated by Django 5.2.12 on 2026-03-19 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="empresa",
            unique_together={("cnpj", "organization")},
        ),
    ]
