# Generated by Django 5.2.12 on 2026-03-18 23:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulacao",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("razao_social", models.CharField(blank=True, default="", max_length=300)),
                ("cnpj", models.CharField(blank=True, default="", max_length=18)),
                ("valor_total_divida", models.DecimalField(decimal_places=2, max_digits=15)),
                ("percentual_previdenciario", models.DecimalField(decimal_places=4, max_digits=5)),
                ("is_me_epp", models.BooleanField(default=False)),
                (
                    "classificacao_credito",
                    models.CharField(
                        choices=[
                            ("A", "A - Alta recuperação"),
                            ("B", "B - Média recuperação"),
                            ("C", "C - Difícil recuperação"),
                            ("D", "D - Irrecuperável"),
                        ],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("resultado", models.JSONField(default=dict)),
                ("calculo_detalhes", models.JSONField(default=dict)),
                ("versao_calculo", models.CharField(default="1.0", max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulacoes",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="simulacoes", to="core.organization"
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulação Básica",
                "verbose_name_plural": "Simulações Básicas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimulacaoAvancada",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("passivo_rfb", models.DecimalField(decimal_places=2, max_digits=15)),
                ("capag_60m", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "desconto_escolha",
                    models.CharField(
                        choices=[("MAIOR", "Maior desconto"), ("MENOR", "Menor desconto")],
                        default="MAIOR",
                        max_length=10,
                    ),
                ),
                ("previdenciario_principal", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("previdenciario_multa", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("previdenciario_juros", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("previdenciario_encargos", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("tributario_principal", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("tributario_multa", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("tributario_juros", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("tributario_encargos", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("simples_principal", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("simples_multa", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("simples_juros", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("simples_encargos", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("resultado", models.JSONField(default=dict)),
                ("calculo_detalhes", models.JSONField(default=dict)),
                ("versao_calculo", models.CharField(default="1.0", max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulacoes_avancadas",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulacoes_avancadas",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulação Avançada",
                "verbose_name_plural": "Simulações Avançadas",
                "ordering": ["-created_at"],
            },
        ),
    ]
