# Generated by Django 5.2.12 on 2026-03-18 23:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndiceEconomico",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "serie_codigo",
                    models.IntegerField(
                        db_index=True, help_text="Código da série BCB SGS (ex: 4390=SELIC mensal, 433=IPCA)"
                    ),
                ),
                (
                    "serie_nome",
                    models.CharField(help_text="Nome descritivo da série (ex: 'SELIC mensal')", max_length=100),
                ),
                ("data_referencia", models.DateField(db_index=True, help_text="Data de referência do índice")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=6, help_text="Valor do índice (ex: 0.870000 para 0.87%)", max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Índice Econômico",
                "verbose_name_plural": "Índices Econômicos",
                "ordering": ["serie_codigo", "data_referencia"],
                "unique_together": {("serie_codigo", "data_referencia")},
            },
        ),
    ]
